#!/bin/bash
# AQE v3 Worker Daemon Startup Script
# Generated by aqe init

PROJECT_ROOT="c:\Projects\agentic-qe"
WORKERS_DIR="$PROJECT_ROOT/.agentic-qe/workers"
PID_FILE="$WORKERS_DIR/daemon.pid"

# Check if already running
if [ -f "$PID_FILE" ]; then
  PID=$(cat "$PID_FILE")
  if kill -0 "$PID" 2>/dev/null; then
    echo "Daemon already running (PID: $PID)"
    exit 0
  fi
fi

# Start daemon (AQE v3 native - no claude-flow dependency)
# TODO: Implement aqe daemon command for background workers
# For now, hooks work via CLI without daemon
echo "AQE v3 hooks work via CLI commands (no daemon required)"
echo "Use: npx aqe hooks session-start"
